//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package api

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(AgentCron)
		**out = **in
	}
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(AgentLLM)
		**out = **in
	}
	if in.Gitea != nil {
		in, out := &in.Gitea, &out.Gitea
		*out = new(AgentGitea)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(AgentKubernetes)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(AgentResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(AgentMemory)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCron) DeepCopyInto(out *AgentCron) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCron.
func (in *AgentCron) DeepCopy() *AgentCron {
	if in == nil {
		return nil
	}
	out := new(AgentCron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLLM) DeepCopyInto(out *AgentLLM) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLLM.
func (in *AgentLLM) DeepCopy() *AgentLLM {
	if in == nil {
		return nil
	}
	out := new(AgentLLM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentGitea) DeepCopyInto(out *AgentGitea) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentGitea.
func (in *AgentGitea) DeepCopy() *AgentGitea {
	if in == nil {
		return nil
	}
	out := new(AgentGitea)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentKubernetes) DeepCopyInto(out *AgentKubernetes) {
	*out = *in
	if in.NamespaceAccess != nil {
		in, out := &in.NamespaceAccess, &out.NamespaceAccess
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentKubernetes.
func (in *AgentKubernetes) DeepCopy() *AgentKubernetes {
	if in == nil {
		return nil
	}
	out := new(AgentKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentResources) DeepCopyInto(out *AgentResources) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceRequirements)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceRequirements)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentResources.
func (in *AgentResources) DeepCopy() *AgentResources {
	if in == nil {
		return nil
	}
	out := new(AgentResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMemory) DeepCopyInto(out *AgentMemory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMemory.
func (in *AgentMemory) DeepCopy() *AgentMemory {
	if in == nil {
		return nil
	}
	out := new(AgentMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AgentCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GiteaUser != nil {
		in, out := &in.GiteaUser, &out.GiteaUser
		*out = new(GiteaUserStatus)
		**out = **in
	}
	if in.LastAction != nil {
		in, out := &in.LastAction, &out.LastAction
		*out = new(AgentLastAction)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenUsage != nil {
		in, out := &in.TokenUsage, &out.TokenUsage
		*out = new(AgentTokenUsage)
		**out = **in
	}
	if in.CurrentTask != nil {
		in, out := &in.CurrentTask, &out.CurrentTask
		*out = new(CurrentTask)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCondition) DeepCopyInto(out *AgentCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCondition.
func (in *AgentCondition) DeepCopy() *AgentCondition {
	if in == nil {
		return nil
	}
	out := new(AgentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GiteaUserStatus) DeepCopyInto(out *GiteaUserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GiteaUserStatus.
func (in *GiteaUserStatus) DeepCopy() *GiteaUserStatus {
	if in == nil {
		return nil
	}
	out := new(GiteaUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLastAction) DeepCopyInto(out *AgentLastAction) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLastAction.
func (in *AgentLastAction) DeepCopy() *AgentLastAction {
	if in == nil {
		return nil
	}
	out := new(AgentLastAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTokenUsage) DeepCopyInto(out *AgentTokenUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTokenUsage.
func (in *AgentTokenUsage) DeepCopy() *AgentTokenUsage {
	if in == nil {
		return nil
	}
	out := new(AgentTokenUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentTask) DeepCopyInto(out *CurrentTask) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentTask.
func (in *CurrentTask) DeepCopy() *CurrentTask {
	if in == nil {
		return nil
	}
	out := new(CurrentTask)
	in.DeepCopyInto(out)
	return out
}
